# Generated by Django 3.0.9 on 2020-11-11 06:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crud_app', '0002_auto_20201109_0901'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employeedata',
            name='name',
            field=models.CharField(max_length=20, unique=True),
        ),
    ]
